### PR TITLE
Get the project going again

### PR DESCRIPTION
**Pull request by theclapp**
Many updates. As the PR title says, get the project going again. Read the commit msgs, but be advised that I made no effort to clean up the commit log, and in particular once or twice I wrote and committed a bunch of code and then later ripped it out again or substantially refactored it. So don't sweat the details of a particular commit unless you've made sure that code is in the final PR. (But after that, sure, go wild. :)

Move the demo & giodemo code to separate repositories. Having them in this one made it confusing to run, what with having the reloader and the demo code in the same tree.

The current code works with the terminal-based demo, and the Gio-based demo too, and it can filter, compile, and run a significantly larger application, but there are still some bugs (either locally or in Yaegi) that make reloading some functions in that larger app return errors from the interpreter, or even panic it.

### CODE REVIEW

**Comment by theclapp** [comment]
I updated the README with how to run the demo, but, tbh, I pulled that out of my 🍑 and haven't verified that it works.

Here's how I actually run the demo:

```sh
cd .../path/to/github.com/got-reload/demo
( cd ../got-reload/cmd/got-reload && go install -v . ) \
&& rm -rf /tmp/got-reload/* \
&& got-reload run -dir /tmp/got-reload -v \
   -p github.com/got-reload/demo/example,github.com/got-reload/demo/example2 \
   github.com/got-reload/demo
```

**Comment by whereswaldon** [comment]
@theclapp Right now I'm not going to be able to help with this project. :disappointed:  There's too much else going on. Feel free to forge ahead without me. :fire: :hammer_and_pick: :fire:

**Comment by theclapp** [comment]
Related Yaegi bugs: https://github.com/traefik/yaegi/issues/1623, https://github.com/traefik/yaegi/issues/1632.

**Comment by theclapp** [comment]
I think I've gone as far as I can for the moment. Gonna go ahead and merge.

**Pull request merged**
